### ISSUE TITLE
A couple issues with mobile windows

### ISSUE THREAD

**Issue by Br0ad** [BlackDeluxeCat/MI2-Utilities-Java#1]
1.Make  a setting so that the title bar of each window will stay up. And make it automatically on

2.if main window is snapped to another window thats been closed it will be stuck and you won't be able to open title.

**Comment by BlackDeluxeCat** [comment]
For 1, I will add a window-independent setting in next release.
For 2, I couldn't reproduce it. Any screenshot? Title opens once you touch any area of the window for 0.25s+, and snapping has nothing to do with it.

(For some reason expansion get interrupted if touching any buttons. Hold on and it will finally open. )

**Comment by Br0ad** [comment]
Ok thanks I will try to reproduce again if possible

**Comment by Br0ad** [comment]
Fixed
