### ISSUE TITLE
crash on start-up on mobile.

### ISSUE THREAD

**Issue by XVIsys** [BlackDeluxeCat/MI2-Utilities-Java#10]
Crashes started after playing around with some AI settings then reloading. Cause is unknown.

**Comment by XVIsys** [comment]
Unable to attach save data or crash logs.

**Comment by BlackDeluxeCat** [comment]
hard to fix it without crash logs
what is the version of mod?

**Comment by XVIsys** [comment]
The problem was in 1.5.5. though it seems to have been an issue already fixed in 1.5.5b. I have not had the issue since I updated to 1.5.5b.
