### ISSUE TITLE
一些bug

### ISSUE THREAD

**Issue by PTALTS-LK** [BlackDeluxeCat/MI2-Utilities-Java#11]
mi2u版本:1.5.5b-146
在be24780测试

尝试滑动ai面板中的自动修复滑块会使整个面板跟随鼠标运动
![image](https://github.com/BlackDeluxeCat/MI2-Utilities-Java/assets/62936489/1ad96edf-4198-4842-88d9-b8d5d17b5775)

屏边移动视角功能会在除了游戏界面的地方工作(比如logic编辑界面,esc菜单界面)

**Comment by BlackDeluxeCat** [comment]
Fixed in 4565836
