### ISSUE TITLE
Feature Request: Color-code turret zones to match turret color

### ISSUE THREAD

**Issue by shinohara-rin** [BlackDeluxeCat/MI2-Utilities-Java#12]
Thanks for the amazing mod! 

The turret zone display is excellent, but it could be better if each zone was color-coded to match the turret color.

For instance, Duo zones could be grey, and Lance zones could be blue.

**Comment by shinohara-rin** [comment]
![iw](https://github.com/BlackDeluxeCat/MI2-Utilities-Java/assets/25588514/a9b02dcd-4b77-49cb-88b4-f59ae8ee1f2f)
Just a quick demo of my idea, not sure if it'll work well.

**Comment by shinohara-rin** [comment]
Well, maybe another approach is to color-code turrets to match their anti-ground/anti-air capability.

**Comment by shinohara-rin** [comment]
![image](https://github.com/BlackDeluxeCat/MI2-Utilities-Java/assets/25588514/dea7e805-f965-4d42-af12-4a6cf9d777ac)
I tried to implement this my self, however there seems to be some problem, stacking multiple turret zones causes them to quickly become kinda opaque and hide any underlying zones.

**Comment by BlackDeluxeCat** [comment]
Added in 1.6.2
