### ISSUE TITLE
Updater issue

### ISSUE THREAD

**Issue by 5UP3R-D1N** [BlackDeluxeCat/MI2-Utilities-Java#2]
Client : Foos v142
Mod : [v1.1.8](https://github.com/BlackDeluxeCat/MI2-Utilities-Java/releases/tag/1.1.8) (Trying to upgrade to v1.2.1b)
Error : 
![image](https://user-images.githubusercontent.com/42496449/227450093-734cf9cd-0f84-42dc-85de-826ed8a84225.png)

**Comment by BlackDeluxeCat** [comment]
[1.2.2](https://github.com/BlackDeluxeCat/MI2-Utilities-Java/releases/tag/1.2.2) Fixed.
