### ISSUE TITLE
关于rts编队功能

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [BlackDeluxeCat/MI2-Utilities-Java#3]
## 1.编队和选中快捷键在原版端143.1无法生效；改端143.1的编队快捷键可用，但还是不能快速选中；通过ui点击以上功能可正常使用
(均未修改过键位，且每次测试前已删除C:\Users\Administrator\AppData\Roaming\Mindustry 模拟全新用户)

## 2.希望mi2u的编队功能可以像蓝图功能一样提供一个拆分的独立版本
mi2u在原版端或配合大型mod食用很好，但在改端上会有功能和ui的重叠，故希望可以有一个拆分出的编队功能，以实现更灵活的使用

## 3.功能建议-强制攻击和强制移动
前者类似其他rts游戏中的“a地板”，可以不用逻辑辅助的情况下使collaris等兵种实现超射程攻击白嫖
类似mdt里逻辑的ucontrol target x y，向指定位置射击但不移动
预想：可以选中部队后，摁住一个快捷键并用鼠标右击下达此命令(建议可以自定义快捷键，以符合不同rts游戏玩家的习惯)

后者类似mdt里逻辑的ucontrol move x y，强制直线移动
可以在寻路原地打转时使兵种直线移动，越过深水等，至于会不会淹死就是玩家操控问题了(
预想：可以选中部队后，摁住一个快捷键并用鼠标右击下达此命令(建议可以自定义快捷键，以符合不同rts游戏玩家的习惯)

至于为何二者不使用逻辑，是因为用了逻辑就没法灵活分兵了(
以上两个功能即使没法在服务器上用，对单机游戏的体验的提升也很大，希望mi2大佬喜欢的话阔以考虑做一下

**Comment by BlackDeluxeCat** [comment]
感谢你的反馈和建议。

>1.
下个版本将修复。

>2.3.

本mod玩家操作均基于原版，你建议的新功能也许只能提供给玩家机。
几个窗口具有很高的自由度，UI如果重叠，请拖拽移动米2u的各个窗口，然后保存当前位置。
短期内不考虑拆分，因为

1. Anuke在写rts操作了，可以期待一下他的花活。
2. SchematicParse功能独立而且比较“极客”，并不是每个玩家都感兴趣的游戏体验/每个玩家都能学会使用，这类功能适合拆分，MapFilterExt同理。个人看法，360全家桶风格是改端特有的，而不是QOL Mod的。

**Comment by YaeSakuraQvQ** [comment]
了解，感谢大佬
