### ISSUE TITLE
Even more updater issue

### ISSUE THREAD

**Issue by 5UP3R-D1N** [BlackDeluxeCat/MI2-Utilities-Java#4]
java.net.MalformedURLException: no protocol: github.com/BlackDeluxeCat/MI2-Utilities-Java/releases/latest
I think u forgot to add https:// on that fix

**Comment by BlackDeluxeCat** [comment]
[Fixed](https://github.com/BlackDeluxeCat/MI2-Utilities-Java/releases/tag/1.2.3)
