### ISSUE TITLE
AI settings don't work on Erekir or with certain units

### ISSUE THREAD

**Issue by QuentinMcCarthy** [BlackDeluxeCat/MI2-Utilities-Java#6]
Recently downloaded this mod because having more information never hurt, and the AI tools in particular were quite interesting.

But... There's no explanation for what each of the buttons or options do. I can figure some out simply by toggling them, but some don't seem to do anything at all. This is especially apparently with the AI tools. No matter what configuration I have those settings in, nothing happens. I got it to rebuild a couple buildings, but that's it. It doesn't mine, it doesn't repair, it doesn't deposit, it doesn't do anything.

**Comment by QuentinMcCarthy** [comment]
I figured out how to get the AI to work via finally finding the help section, though there's a good few settings that still aren't explained.

Something that's far more important to me, though, is that this mod isn't compatible with Erekir, from the looks of things.

**Comment by QuentinMcCarthy** [comment]
In addition, in any unit that doesn't rotate towards enemies i.e. any unit with independently rotating turrets, don't shoot at enemies with the auto attack setting. They simply shoot where they're facing.

**Comment by BlackDeluxeCat** [comment]
> In addition, in any unit that doesn't rotate towards enemies i.e. any unit with independently rotating turrets, don't shoot at enemies with the auto attack setting. They simply shoot where they're facing.

this will be fixed in the future.


> I figured out how to get the AI to work via finally finding the help section, though there's a good few settings that still aren't explained.
> 
> Something that's far more important to me, though, is that this mod isn't compatible with Erekir, from the looks of things.

not sure about the form of adding help infos. 
miner ai doesn't support wall ore, as how vanilla does.

**Comment by BlackDeluxeCat** [comment]
Enable `Replace Input Handler` to use AI and other player-controll functions.
& New setting system with hints is available.
& Miner AI supports erekir now.
