### ISSUE TITLE
Unminimise

### ISSUE THREAD

**Issue by Jaeyun21** [BlackDeluxeCat/MI2-Utilities-Java#7]
How to unminimise windows?

**Comment by BlackDeluxeCat** [comment]
Minimized window turns into a small button. Click the button to unminimize.

**Comment by BlackDeluxeCat** [comment]
It'is probably a bug fixed in [1.4.2b](https://github.com/BlackDeluxeCat/MI2-Utilities-Java/releases/tag/1.4.2b).
If it still happens, wake me up.
