### ISSUE TITLE
CoreInfo Powerbar is practically invisible unless Show Core Items is enabled

### ISSUE THREAD

**Issue by HazardousMonkey** [BlackDeluxeCat/MI2-Utilities-Java#9]
Visual Example:
![image](https://github.com/BlackDeluxeCat/MI2-Utilities-Java/assets/49216094/e209ae89-8d15-4209-b252-8dd38c684a44)

**Comment by BlackDeluxeCat** [comment]
fixed in [1.5.3](https://github.com/BlackDeluxeCat/MI2-Utilities-Java/releases/tag/1.5.3).
